build:
  environment:
    php: '7.1'

  tests:
    override:
      - true

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - config/*
    - tests/*
    - src/Generated/*
    - src/Pyz/*
